package com.social.media.model;

import jakarta.persistence.*;  // Import for JPA annotations

/**
 * This class represents a social media user.
 * It's a JPA entity and maps to a database table.
 */
@Entity
public class SocialUser {

    /**
     * Unique identifier for the social user (auto-generated by the database).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // Use lowercase 'id' for consistency

    /**
     * Reference to the associated social profile.
     * A one-to-one relationship exists between a social user and a social profile.
     * Mapped by "user" in the SocialProfile class.
     */
    @OneToOne(mappedBy = "user")
    
    private SocialProfile socialProfile;

}