package com.social.media.models;  // Corrected package name (models)

import jakarta.persistence.*;  // Import for JPA annotations
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * This class represents a social media user.
 * It's a JPA entity and maps to a database table.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class  SocialUser {

    /**
     * Unique identifier for the social user (auto-generated by the database).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // Use lowercase 'id' for consistency

    /**
     * Reference to the associated social profile.
     * A one-to-one relationship exists between a social user and a social profile.
     * Mapped by "user" in the SocialProfile class.
     */
    @OneToOne(mappedBy = "user") // Owner class (SocialUser owns the relationship)
    private SocialProfile socialProfile;

    /**
     * Represents a collection of posts created by this user.
     * A one-to-many relationship exists between a social user and their posts.
     * Mapped by "socialUser" in the Post class.
     */
    @OneToMany(mappedBy = "socialUser")
    private List<Post> posts = new ArrayList<>();  // Initialized with an empty ArrayList

    /**
     * Represe  nts the social groups this user belongs to.
     * A many-to-many relationship exists between social users and social groups.
     * A join table named "user_group" is used to map the relationship.
     */
    @ManyToMany
    @JoinTable(
            name = "user_group",
            joinColumns = @JoinColumn(name = "user_id"),
            inverseJoinColumns = @JoinColumn(name = "group_id")
    )
    private Set<SocialGroup> groups = new HashSet<>();  // Initialized with an empty HashSet
}